import { GraphEdge, NodeType } from '../graph/model';
import { ForceParams, SimNode } from '../graph/simulation';
import { Viewport } from '../graph/viewport';
import { NodeScaleParams } from '../graph/node-types';
import { ForceSection } from './GraphControlPanel';
interface GraphCanvasProps {
    nodes: SimNode[];
    edges: GraphEdge[];
    viewport: Viewport;
    onViewportChange: (vp: Viewport) => void;
    onNodeDragStart: (id: string, wx: number, wy: number) => void;
    onNodeDragMove: (wx: number, wy: number) => void;
    onNodeDragEnd: () => void;
    onDoubleClickNode: (id: string) => void;
    onHoverNode: (id: string | null) => void;
    onSelectNode: (id: string | null) => void;
    onNodeContextMenu?: (nodeId: string, clientX: number, clientY: number) => void;
    highlightedNodes: Set<string> | null;
    highlightedEdges: Set<string> | null;
    hoveredNodeId: string | null;
    selectedNodeId: string | null;
    focusedNodeId: string | null;
    searchMatchIds: Set<string> | null;
    running: boolean;
    forceParams: ForceParams;
    activeSection: ForceSection;
    activeChargeType: NodeType | null;
    activeGravityType: NodeType | null;
    activePullEdge: string | null;
    nodeScale: NodeScaleParams;
}
export declare function GraphCanvas({ nodes, edges, viewport, onViewportChange, onNodeDragStart, onNodeDragMove, onNodeDragEnd, onDoubleClickNode, onHoverNode, onSelectNode, onNodeContextMenu, highlightedNodes, highlightedEdges, hoveredNodeId, selectedNodeId, focusedNodeId, searchMatchIds, running, forceParams, activeSection, activeChargeType, activeGravityType, activePullEdge, nodeScale, }: GraphCanvasProps): import("react/jsx-runtime").JSX.Element;
export {};
