// Library build config for `@temporal-architect/visualizer`.
//
// This is the npm-publishable artifact: an ESM bundle with externalized React
// peer dependencies, a single sibling stylesheet, and bundled `.d.ts` files
// generated by vite-plugin-dts. The VS Code webview IIFE bundle is built in the
// distribution repo (packages/webview) from this published library.
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import dts from 'vite-plugin-dts'
import { resolve } from 'path'

export default defineConfig({
  plugins: [
    react(),
    dts({
      // Emit a single bundled `.d.ts` so consumers' IDEs aren't tempted to
      // suggest deep imports into our internal file tree.
      rollupTypes: true,
      // Only include the entry point and its transitive type graph.
      include: ['src/lib.ts', 'src/types/**/*.ts', 'src/components/**/*.tsx', 'src/filter/**/*.ts', 'src/graph/**/*.ts', 'src/theme/**/*.ts'],
      exclude: ['src/App.tsx', 'src/main.tsx', '**/*.test.*'],
      // The DTS plugin defaults to the same outDir as the JS build (dist-lib);
      // we ship the resulting `lib.d.ts` alongside `lib.js`.
    }),
  ],
  resolve: {
    alias: {
      '@': resolve(__dirname, 'src'),
    },
  },
  build: {
    outDir: 'dist-lib',
    emptyOutDir: true,
    sourcemap: true,
    // CSS is emitted as a sibling asset (styles.css). Consumers import it
    // explicitly per the README — we don't auto-inject so host apps can route
    // it through their own pipeline (purge, theme overrides, SSR).
    cssCodeSplit: false,
    lib: {
      entry: resolve(__dirname, 'src/lib.ts'),
      formats: ['es'],
      fileName: () => 'lib.js',
    },
    rollupOptions: {
      // React is a peerDependency — host apps provide their own copy and
      // bundling ours would risk multiple-React-instance bugs (hooks would
      // throw at runtime). Same for react-dom.
      external: ['react', 'react-dom', 'react/jsx-runtime', 'react-dom/client'],
      output: {
        globals: {
          react: 'React',
          'react-dom': 'ReactDOM',
        },
        assetFileNames: (assetInfo) => {
          if (assetInfo.name?.endsWith('.css')) {
            return 'styles.css'
          }
          return 'assets/[name].[ext]'
        },
      },
    },
  },
})
