// The structural map — the facts I kept re-deriving by hand.
//
// Not a gate. It answers, in one read, the three questions that otherwise cost a
// grep-and-read cycle each and that I got wrong more than once: which zone a file
// is in (manifest / shim / neither), what its leak count is, and **who imports
// it**. The reverse index is the valuable half: "what breaks if this moves" is
// the question every unit of this run asks, and grepping for it is both slower
// and, as Unit 2 proved twice, error-prone — one grep excluded the file it was
// searching and hid a symbol's only reader.
//
// Regenerated by `npm run map`, and checked by `--check`, so it cannot go stale
// silently. Zero dependencies (C2).

import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { manifestFiles, shimFiles, readLines, PKG_ROOT } from './manifest.mjs'

const PATTERN =
  /workflow|activity|activities|worker|namespace|nexus|temporal|twf|signalsend|dispatchkind|taskqueue/gi
const URL_LINE = /https?:\/\//
const OUT = 'kickoff/MAP.md'

// Every .ts/.tsx under src/, so "neither" files are visible too — a file in no
// zone is exactly the kind of thing that grows unnoticed.
function allSources(dir = 'src', out = []) {
  for (const name of readdirSync(resolve(PKG_ROOT, dir)).sort()) {
    const rel = `${dir}/${name}`
    if (statSync(resolve(PKG_ROOT, rel)).isDirectory()) allSources(rel, out)
    else if (/\.tsx?$/.test(name)) out.push(rel)
  }
  return out
}
const IMPORT = /(?:\bfrom\s*|^\s*import\s*|\bimport\s*\(\s*|\brequire\s*\(\s*)['"]([^'"]+)['"]/g

function importsOf(file) {
  const text = readLines(file).join('\n')
  const specs = new Set()
  for (const m of text.matchAll(IMPORT)) if (m[1].startsWith('.')) specs.add(m[1])
  return [...specs]
}

function resolveSpec(fromFile, spec) {
  const base = resolve(PKG_ROOT, fromFile, '..', spec)
  for (const ext of ['.ts', '.tsx', '', '/index.ts', '/index.tsx']) {
    const c = base + ext
    if (existsSync(c) && statSync(c).isFile()) return c.slice(resolve(PKG_ROOT).length + 1)
  }
  return null
}

function leakCount(file) {
  let n = 0
  for (const line of readLines(file)) {
    if (URL_LINE.test(line)) continue
    n += (line.match(PATTERN) ?? []).length
  }
  return n
}

const manifest = new Set(manifestFiles())
const shim = new Set(shimFiles())
const zoneOf = f => (manifest.has(f) ? 'manifest' : shim.has(f) ? 'shim' : 'neither')

const sources = allSources()
const importers = new Map(sources.map(f => [f, []]))
for (const f of sources) {
  for (const spec of importsOf(f)) {
    const target = resolveSpec(f, spec)
    if (target && importers.has(target)) importers.get(target).push(f)
  }
}

const lines = []
lines.push('# Structural map — generated, do not edit')
lines.push('')
lines.push('`npm run map` regenerates this; `npm run map -- --check` fails if it is stale.')
lines.push('It is not a gate. It exists because "who imports this" and "which zone is')
lines.push('this in" were being answered by grep, repeatedly, and wrongly.')
lines.push('')
lines.push('**zone** — `manifest` is the library-to-be (the three ratchets measure it and')
lines.push("Unit 8 moves it); `shim` is the host half; `neither` is measured by nothing,")
lines.push('which is worth noticing rather than assuming.')
lines.push('')
lines.push('| file | zone | leak | imported by |')
lines.push('|---|---|---:|---|')
for (const f of sources) {
  const who = importers.get(f)
  const by = who.length === 0 ? '—' : who.length <= 3 ? who.map(w => `\`${w.replace('src/', '')}\``).join(', ') : `**${who.length}** files`
  lines.push(`| \`${f.replace('src/', '')}\` | ${zoneOf(f)} | ${leakCount(f) || ''} | ${by} |`)
}
lines.push('')
lines.push('## Files nothing imports')
lines.push('')
lines.push('An entry point, dead code, or a symbol whose only reader is the harness —')
lines.push('the third is F15, and no gate counts readers.')
lines.push('')
for (const f of sources) if (importers.get(f).length === 0) lines.push(`- \`${f}\` (${zoneOf(f)})`)
lines.push('')

const body = lines.join('\n')
const path = resolve(PKG_ROOT, OUT)

if (process.argv.includes('--check')) {
  let current = ''
  try { current = readFileSync(path, 'utf8') } catch { /* missing */ }
  if (current !== body) {
    console.error(`FAIL ${OUT} is stale. Run \`npm run map\`.`)
    process.exit(1)
  }
  console.log(`${OUT}: up to date`)
} else {
  writeFileSync(path, body)
  console.log(`wrote ${OUT} — ${sources.length} source files`)
}
