package main

import (
	"bytes"
	"os"
	"sort"
	"strings"

	"github.com/jmbarzee/temporal-architect/tools/lsp/cmd/twf/internal/cmdutil"
	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

//go:generate go run . gen-docs --out COMMANDS.md

// docsHeader is prepended to the generated reference. It marks the file as
// generated so reviewers know not to hand-edit it, and points at the source of
// truth (the command definitions) and the regen command.
const docsHeader = `<!-- Code generated by ` + "`make gen-docs`" + `; DO NOT EDIT. -->
<!-- Source of truth: the cobra command definitions in tools/lsp/cmd/twf. -->

# twf command reference

This page is generated from the ` + "`twf`" + ` command tree. Run ` + "`make gen-docs`" + ` to
refresh it; CI fails if it drifts from the binary. Conceptual material (the JSON
envelope shape, node-ID grammar, edge kinds, diagnostic codes) lives in the
hand-authored [README](./README.md).

`

// newGenDocsCmd builds the hidden `gen-docs` command. It renders the whole
// command tree into a single, deterministic markdown file via cobra/doc.
// It is Hidden so it never appears in user-facing help or the generated
// reference itself.
func newGenDocsCmd() *cobra.Command {
	var out string
	cmd := cmdutil.Silence(&cobra.Command{
		Use:    "gen-docs",
		Short:  "Generate the command reference (internal)",
		Hidden: true,
		Args:   cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			md, err := renderDocs(cmd.Root())
			if err != nil {
				return err
			}
			return os.WriteFile(out, []byte(md), 0o644)
		},
	})
	cmd.Flags().StringVar(&out, "out", "COMMANDS.md", "Output markdown file path")
	return cmd
}

// renderDocs walks the command tree and concatenates per-command markdown into
// one file. It strips cobra/doc's dated "Auto generated" footer (which would
// otherwise make the output non-deterministic and break the CI drift gate) and
// rewrites cross-file SEE-ALSO links into intra-document anchors.
func renderDocs(root *cobra.Command) (string, error) {
	var buf bytes.Buffer
	buf.WriteString(docsHeader)

	linkHandler := func(name string) string {
		// cobra/doc passes a filename like "twf_graph_chunks.md"; map it to the
		// anchor GitHub derives from the "## twf graph chunks" heading.
		base := strings.TrimSuffix(name, ".md")
		return "#" + strings.ReplaceAll(base, "_", "-")
	}

	var walk func(c *cobra.Command) error
	walk = func(c *cobra.Command) error {
		if c.Hidden || !c.IsAvailableCommand() {
			return nil
		}
		var section bytes.Buffer
		if err := doc.GenMarkdownCustom(c, &section, linkHandler); err != nil {
			return err
		}
		buf.WriteString(stripGeneratedFooter(section.String()))

		children := c.Commands()
		sort.Slice(children, func(i, j int) bool { return children[i].Name() < children[j].Name() })
		for _, child := range children {
			if err := walk(child); err != nil {
				return err
			}
		}
		return nil
	}
	if err := walk(root); err != nil {
		return "", err
	}
	return buf.String(), nil
}

// stripGeneratedFooter removes cobra/doc's trailing dated provenance line so the
// output is byte-stable across runs.
func stripGeneratedFooter(s string) string {
	lines := strings.Split(s, "\n")
	kept := lines[:0]
	for _, ln := range lines {
		if strings.HasPrefix(ln, "###### Auto generated by spf13/cobra") {
			continue
		}
		kept = append(kept, ln)
	}
	out := strings.Join(kept, "\n")
	return strings.TrimRight(out, "\n") + "\n\n"
}
